[features]
seeds = false
[programs.localnet]
dicsionaly = "HzTE8qTtPxhTN2kzSCpfY9FSbYt8rt72pgBzinbUMKbL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/regonn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
